### ISSUE TITLE
Quiz question on cats/dogs

### ISSUE THREAD

**Issue by tmontobbio** [learn-co-curriculum/phase-3-quiz-arrays-and-hashes#2]
### Canvas Link

https://learning.flatironschool.com/courses/5215/quizzes/36101

### Concern

I believe the question about dogs and cats not getting along and returning an array of cats is biased! Maybe make it so the correct answer is an array of cats OR dogs.

;)

just kidding, but also seriously!

**Comment by lizbur10** [comment]
Hi @tmontobbio ! Thank you for passing along this feedback - we definitely don't want the cats or dogs to feel they are being excluded or discriminated against! I have modified the question to hopefully reduce the bias. 

Note that you may not see the new version in your Canvas course since students have already taken the quiz. However, the changes will be present for future students.
